### ISSUE TITLE
Can't shut off or remove

### ISSUE THREAD

**Issue by jimmiedave** [PhilippC/kp2a_accservice_autofill#16] opened 2018-06-13 23:33 UTC
I'm unable to disable this service in kp2a (application settings>autofill service says "enabled" and won't disable, other autofill and plugin menus lead to web sites), unable to see it in Android accessibility services, unable to find it in Android app manager.

I'm on Android 8.0.0 on an HTC M10.

The main thing this service does for me is get in the way of the UI for VX Connectbot and the phone dialer. It's a problem (that's the most polite thing I can say) that I can't disable it if not outright remove it.

**Comment by lupalby** [comment] 2018-06-13 23:38
Duplicate of issue https://github.com/PhilippC/kp2a_accservice_autofill/issues/14

**Comment by jimmiedave** [comment] 2018-06-13 23:49
You should make an intent or whatever  in kp2a that does this. I'd looked multiple times over the last couple months to try and shut it off. Wouldn't have thought to search for closed issues,

**Comment by PhilippC** [comment] 2018-06-25 08:47
this is the wrong project

**Closed by PhilippC** 2018-06-25 08:47 UTC
