### ISSUE TITLE
Autofill doesn't work after update to Android 13

### ISSUE THREAD

**Issue by litmich** [PhilippC/kp2a_accservice_autofill#42] opened 2022-12-11 06:25 UTC
Since update to Android 13 (Note 10 lite) , with auto fill plugin.
With some apps works as intended.
Some only raise notification for auto fill,  but no popup, even after selecting "auto fill" submenu of the input field.
Some show suggestion inlined in a swift keyboard,  some not.
Some apps seem not to be recognised as target for autofill at all, no autofill prompt in any form. Only switch to key pass keyboard helps.
[Also here](https://github.com/PhilippC/keepass2android/issues/2132#issuecomment-1345468570)

**Comment by PhilippC** [comment] 2023-03-06 11:03
closing as duplicate of https://github.com/PhilippC/keepass2android/issues/2059

**Closed as completed by PhilippC** 2023-03-06 11:03 UTC
